_BASE_: ../Base-SBS.yml

INPUT:
  SIZE_TRAIN: [384, 384]
  SIZE_TEST: [384, 384]
MODEL:
  BACKBONE:
    DEPTH: 101x
    WITH_IBN: True
    WITH_NL: True
  WEIGHTS: "./logs/Patent/R101_384/model_best.pth"

SOLVER:
  BIAS_LR_FACTOR: 1.
  BASE_LR: 0.000035
  IMS_PER_BATCH: 64
  MAX_EPOCH: 60
  STEPS: [10, 20]
  WARMUP_ITERS: 3000
  CHECKPOINT_PERIOD: 5


DATASETS:
  NAMES: ("PatentTest",)
  TESTS: ("PatentTest",)

DATALOADER:
  SAMPLER_TRAIN: BalancedIdentitySampler
TEST:
  EVAL_PERIOD: 5
  IMS_PER_BATCH: 32 #128
  AQE:
    ENABLED: True
    ALPHA : 2.0
    QE_TIME : 1
    QE_K: 5
OUTPUT_DIR: logs/Patent/submit_log