_BASE_: ../Base-SBS.yml

INPUT:
  SIZE_TRAIN: [256, 256]
  SIZE_TEST: [256, 256]

MODEL:
  BACKBONE:
    WITH_IBN: True
    WITH_NL: True
  WEIGHTS: "/media/backup/competition/eccv_retrieve/fast-reid/logs/Patent/sbs_R50-ibn/model_best.pth" #"/media/backup/competition/eccv_retrieve/fast-reid/logs/Patent/sbs_R50-ibn/model_best.pth"
SOLVER:
  OPT: SGD
  BASE_LR: 0.01
  ETA_MIN_LR: 7.7e-5

  IMS_PER_BATCH: 128
  MAX_EPOCH: 60
  WARMUP_ITERS: 3000
  FREEZE_ITERS: 3000

  CHECKPOINT_PERIOD: 5

DATASETS:
  NAMES: ("Patent",)
  TESTS: ("Patent",)

DATALOADER:
  SAMPLER_TRAIN: BalancedIdentitySampler

TEST:
  EVAL_PERIOD: 5
  IMS_PER_BATCH: 256
  AQE:
    ALPHA: 2.0
    ENABLED: True
    QE_K: 5
    QE_TIME: 1
OUTPUT_DIR: logs/Patent/sbs_R50-ibn/test
