_BASE_: ../Base-SBS.yml

INPUT:
  SIZE_TRAIN: [256, 256]
  SIZE_TEST: [256, 256]
MODEL:
  BACKBONE:
    DEPTH: 101x
    WITH_IBN: True
    WITH_NL: True
SOLVER:
  BIAS_LR_FACTOR: 1.
  BASE_LR: 0.00035
  IMS_PER_BATCH: 64
  MAX_EPOCH: 60
  STEPS: [25, 35]
  WARMUP_ITERS: 3000
  CHECKPOINT_PERIOD: 5

# SOLVER:
#   OPT: SGD
#   BASE_LR: 0.01
#   ETA_MIN_LR: 7.7e-5
#   IMS_PER_BATCH: 128
#   MAX_EPOCH: 60
#   WARMUP_ITERS: 3000
#   FREEZE_ITERS: 3000
#   CHECKPOINT_PERIOD: 5
DATASETS:
  NAMES: ("Patent",)
  TESTS: ("Patent",)

DATALOADER:
  SAMPLER_TRAIN: BalancedIdentitySampler
TEST:
  EVAL_PERIOD: 5
  IMS_PER_BATCH: 128 
  # FLIP: 
  #   ENABLED: True
  AQE:
    ENABLED: False
    ALPHA : 2.0
    QE_TIME : 1
    QE_K: 5


OUTPUT_DIR: logs/Patent/R101_256